package openwrightcore

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"os"
	"testing"
)

// TestConformance proves the Go core reproduces the Python core byte-for-byte.
// The vectors are generated by conformance/generate_vectors.py (Python is the
// single source of truth). Any divergence here fails the build — the gate that
// keeps a second implementation from silently drifting (Option C).
//
// It strictly checks all FIVE vector categories:
//   canonical    — canonical encoding + leaf hash of arbitrary values
//   merkle       — tree root + inclusion proofs
//   consistency  — consistency proofs (verify committed proofs AND reproduce them)
//   timestamps   — ToRFC3339 integer normalization
//   events       — full ComplianceEvent leaf-content serialization + leaf hash

type canonVec struct {
	Input     json.RawMessage `json:"input"`
	Canonical string          `json:"canonical"`
	LeafHash  string          `json:"leaf_hash"`
}

type inclVec struct {
	Index int      `json:"index"`
	Proof []string `json:"proof"`
}

type merkleVec struct {
	Leaves    []string  `json:"leaves"`
	Root      string    `json:"root"`
	Inclusion []inclVec `json:"inclusion"`
}

type consistencyProofVec struct {
	First  int      `json:"first"`
	Second int      `json:"second"`
	Proof  []string `json:"proof"`
}

type consistencyVec struct {
	Leaves []string              `json:"leaves"`
	Root   string                `json:"root"`
	Proofs []consistencyProofVec `json:"proofs"`
}

type timestampVec struct {
	Value   int64  `json:"value"`
	RFC3339 string `json:"rfc3339"`
}

type eventVec struct {
	Event     json.RawMessage `json:"event"`
	EventID   string          `json:"event_id"`
	Canonical string          `json:"canonical"`
	LeafHash  string          `json:"leaf_hash"`
}

type vectorFile struct {
	Canonical   []canonVec       `json:"canonical"`
	Merkle      []merkleVec      `json:"merkle"`
	Consistency []consistencyVec `json:"consistency"`
	Timestamps  []timestampVec   `json:"timestamps"`
	Events      []eventVec       `json:"events"`
	EmptySha    string           `json:"empty_sha256"`
}

func decodeNum(raw []byte) (interface{}, error) {
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.UseNumber()
	var v interface{}
	if err := dec.Decode(&v); err != nil {
		return nil, err
	}
	return v, nil
}

func hexProof(p [][]byte) []string {
	out := make([]string, len(p))
	for i, h := range p {
		out[i] = hex.EncodeToString(h)
	}
	return out
}

func TestConformance(t *testing.T) {
	data, err := os.ReadFile("../conformance/vectors.json")
	if err != nil {
		t.Fatalf("read vectors: %v", err)
	}
	var v vectorFile
	if err := json.Unmarshal(data, &v); err != nil {
		t.Fatalf("parse vectors: %v", err)
	}

	// -- canonical ------------------------------------------------------------
	if len(v.Canonical) == 0 {
		t.Fatal("no canonical vectors")
	}
	for i, cv := range v.Canonical {
		input, err := decodeNum(cv.Input)
		if err != nil {
			t.Fatalf("canonical[%d] decode input: %v", i, err)
		}
		got, err := CanonicalBytes(input)
		if err != nil {
			t.Fatalf("canonical[%d]: %v", i, err)
		}
		if string(got) != cv.Canonical {
			t.Errorf("canonical[%d] mismatch:\n got=%q\nwant=%q", i, got, cv.Canonical)
		}
		if lh := hex.EncodeToString(LeafHash(got)); lh != cv.LeafHash {
			t.Errorf("canonical[%d] leaf hash: got=%s want=%s", i, lh, cv.LeafHash)
		}
	}

	// -- merkle: root + inclusion proofs --------------------------------------
	if len(v.Merkle) == 0 {
		t.Fatal("no merkle vectors")
	}
	for i, mv := range v.Merkle {
		leaves := make([][]byte, len(mv.Leaves))
		for j, d := range mv.Leaves {
			leaves[j] = LeafHash([]byte(d))
		}
		if root := hex.EncodeToString(TreeHash(leaves)); root != mv.Root {
			t.Errorf("merkle[%d] root: got=%s want=%s", i, root, mv.Root)
		}
		for _, iv := range mv.Inclusion {
			proof := InclusionProof(leaves, iv.Index)
			if len(proof) != len(iv.Proof) {
				t.Errorf("merkle[%d] incl[%d] length: got=%d want=%d", i, iv.Index, len(proof), len(iv.Proof))
				continue
			}
			for k, p := range proof {
				if hex.EncodeToString(p) != iv.Proof[k] {
					t.Errorf("merkle[%d] incl[%d] step %d mismatch", i, iv.Index, k)
				}
			}
		}
	}

	// -- consistency: reproduce AND verify each committed proof ---------------
	if len(v.Consistency) == 0 {
		t.Fatal("no consistency vectors")
	}
	for i, cv := range v.Consistency {
		leaves := make([][]byte, len(cv.Leaves))
		for j, d := range cv.Leaves {
			leaves[j] = LeafHash([]byte(d))
		}
		secondRoot := TreeHash(leaves)
		if root := hex.EncodeToString(secondRoot); root != cv.Root {
			t.Errorf("consistency[%d] root: got=%s want=%s", i, root, cv.Root)
		}
		for _, pv := range cv.Proofs {
			// (a) ConsistencyProof reproduces the committed proof bytes.
			gen := ConsistencyProof(leaves, pv.First)
			got := hexProof(gen)
			if len(got) != len(pv.Proof) {
				t.Errorf("consistency[%d] proof(%d->%d) length: got=%d want=%d",
					i, pv.First, pv.Second, len(got), len(pv.Proof))
			} else {
				for k := range got {
					if got[k] != pv.Proof[k] {
						t.Errorf("consistency[%d] proof(%d->%d) step %d: got=%s want=%s",
							i, pv.First, pv.Second, k, got[k], pv.Proof[k])
					}
				}
			}
			// (b) VerifyConsistency accepts the committed proof against the roots.
			firstRoot := TreeHash(leaves[:pv.First])
			proofBytes := make([][]byte, len(pv.Proof))
			for k, h := range pv.Proof {
				b, err := hex.DecodeString(h)
				if err != nil {
					t.Fatalf("consistency[%d] proof hex: %v", i, err)
				}
				proofBytes[k] = b
			}
			if !VerifyConsistency(pv.First, pv.Second, firstRoot, secondRoot, proofBytes) {
				t.Errorf("consistency[%d] VerifyConsistency(%d->%d) rejected a committed proof",
					i, pv.First, pv.Second)
			}
			// Negative control: a tampered proof must be rejected.
			if len(proofBytes) > 0 {
				bad := make([][]byte, len(proofBytes))
				copy(bad, proofBytes)
				tampered := append([]byte(nil), bad[0]...)
				tampered[0] ^= 0xff
				bad[0] = tampered
				if VerifyConsistency(pv.First, pv.Second, firstRoot, secondRoot, bad) {
					t.Errorf("consistency[%d] VerifyConsistency(%d->%d) accepted a tampered proof",
						i, pv.First, pv.Second)
				}
			}
		}
	}

	// -- timestamps: integer normalization ------------------------------------
	if len(v.Timestamps) == 0 {
		t.Fatal("no timestamp vectors")
	}
	for i, tv := range v.Timestamps {
		if got := ToRFC3339(tv.Value); got != tv.RFC3339 {
			t.Errorf("timestamp[%d] ToRFC3339(%d): got=%s want=%s", i, tv.Value, got, tv.RFC3339)
		}
	}

	// -- events: full ComplianceEvent leaf-content serialization --------------
	if len(v.Events) == 0 {
		t.Fatal("no event vectors")
	}
	for i, ev := range v.Events {
		var e Event
		if err := json.Unmarshal(ev.Event, &e); err != nil {
			t.Fatalf("event[%d] unmarshal: %v", i, err)
		}
		cb, err := e.CanonicalBytes()
		if err != nil {
			t.Fatalf("event[%d] canonical: %v", i, err)
		}
		if string(cb) != ev.Canonical {
			t.Errorf("event[%d] canonical mismatch:\n got=%q\nwant=%q", i, cb, ev.Canonical)
		}
		lh, err := e.LeafHash()
		if err != nil {
			t.Fatalf("event[%d] leaf hash: %v", i, err)
		}
		if h := hex.EncodeToString(lh); h != ev.LeafHash {
			t.Errorf("event[%d] leaf hash: got=%s want=%s", i, h, ev.LeafHash)
		}
	}

	// -- empty tree -----------------------------------------------------------
	if er := hex.EncodeToString(EmptyRoot()); er != v.EmptySha {
		t.Errorf("empty root: got=%s want=%s", er, v.EmptySha)
	}
}
